version: "3"
networks:
  dev:
volumes:
  data:
services:
  app:
    build:
      context: .
      dockerfile: ./docker/prod.Dockerfile
    volumes:
      - ./app:/go/src/dev/app
    ports:
      - 8000:8000
    networks:
      - dev
    depends_on:
      - redis
  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    logging:
      driver: none
    volumes:
      - data:/data
    networks:
      - dev
