version: "3"
networks:
  dev:
volumes:
  data:
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/dev.Dockerfile
    volumes:
      - ./app:/go/src/dev/app
    ports:
      - 8000:8000
    networks:
      - dev
