version: "3"
networks:
  dev:
volumes:
  data:
services:
  godev:
    container_name: godev
    build:
      args:
        folder: godev
      context: .
      dockerfile: ./docker/dev.Dockerfile
    volumes:
      - ./src:/go/src/godev/src
    ports:
      - 8000:8000
    networks:
      - dev
